# version: "3.8"

services:
    nginx:
        image: nginx:1.27.4
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            - db
    php:
        build: ./docker/php
        volumes:
            - ./www:/var/www/html
        environment:
            - PHP_FPM_USER=www-data
            - PHP_FPM_GROUP=www-data
        depends_on:
            - db
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: modx_db
            MYSQL_USER: modx_user
            MYSQL_PASSWORD: modx_pass
        volumes:
            - mysql_data:/var/lib/mysql
volumes:
    mysql_data:
